# Generated by Django 3.2.7 on 2021-09-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_desenvolvedora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desenvolvedora',
            options={'verbose_name_plural': 'Desenvolvedoras'},
        ),
        migrations.AlterModelOptions(
            name='motorgrafico',
            options={'verbose_name_plural': 'Motores Graficos'},
        ),
    ]
