# Generated by Django 3.2.7 on 2021-09-28 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210928_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('classificacao', models.CharField(max_length=20)),
                ('dataLancamento', models.DateField()),
                ('desenvolvedora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jogos', to='core.desenvolvedora')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jogos', to='core.genero')),
            ],
        ),
    ]
