# Generated by Django 3.2.7 on 2021-09-28 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='motorgrafico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='jogos', to='core.motorgrafico'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='desenvolvedora',
        ),
        migrations.AddField(
            model_name='jogo',
            name='desenvolvedora',
            field=models.ManyToManyField(related_name='jogos', to='core.Desenvolvedora'),
        ),
    ]
