# Generated by Django 3.2.7 on 2021-10-04 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='valor',
            field=models.IntegerField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PacoteAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('preco', models.FloatField(max_length=20)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacote', to='core.jogo')),
            ],
        ),
    ]
