# Generated by Django 3.2.7 on 2021-10-04 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20211004_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinatura',
            name='valor',
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Assinaturas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='desenvolvedora',
        ),
        migrations.AddField(
            model_name='jogo',
            name='desenvolvedora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='jogos', to='core.desenvolvedora'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pacoteassinatura',
            name='jogo',
        ),
        migrations.AddField(
            model_name='pacoteassinatura',
            name='jogo',
            field=models.ManyToManyField(related_name='pacote', to='core.Jogo'),
        ),
        migrations.AlterField(
            model_name='pacoteassinatura',
            name='preco',
            field=models.FloatField(),
        ),
    ]
