# Generated by Django 3.2.7 on 2021-10-04 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211004_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('Assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.assinatura')),
                ('PacoteAssinatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.pacoteassinatura')),
            ],
        ),
    ]
